# Generated by Django 5.0.1 on 2024-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[(1, 'Season'), (2, 'Single')], max_length=10),
        ),
    ]
